name: Atualizar status de pagamentos

on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

jobs:
  atualizar-status:
    runs-on: ubuntu-latest
    steps:
      - name: Rodar SQL no Supabase
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
          psql $SUPABASE_DB_URL -c "CALL atualizar_status_pagamento_pendente();"